### ISSUE TITLE
incorrect URL for streaming API

### ISSUE THREAD

**Issue by Johann150** [yupix/MiPA#16]
The framework uses an incorrect URL for the streaming API. The streaming API documentation can be found at: https://misskey-hub.net/docs/api/streaming

wrong: `wss://misskey.example/?i={token}`
correct: `wss://misskey.example/streaming?i={token}`

I think this line needs to be changed:
https://github.com/yupix/MiPA/blob/e53ee6106867702c13b0ac96f8f943abff3bcb5c/mipa/gateway.py#L66

It only works because Misskey is currently permissive about which URL you use. Foundkey (a fork of Misskey) is more restrictive and only allows the path `/streaming` that is defined in the documentation.

**Comment by yupix** [comment]
Thanks for the report. This is probably because Mi.py, the original MiPA, was initially created as a wrapper for just the Misskey API, so the string "streaming" has been removed.

**Comment by yupix** [comment]
I just remembered that in pull request #17, if you include streaming in the url, it may not work correctly as streamingstreaming. Please wait a while until this is resolved.

**Comment by yupix** [comment]
In fixing this bug, we also fixed a bug that caused an error if there was a trailing `/`, such as `https://example.com/`. Thank you again for your report.
