### ISSUE TITLE
サーバ側から切断された際に WebSocket が再接続しない(ように見える)

### ISSUE THREAD

**Issue by yuma-m** [yupix/MiPA#24]
こんにちは、使いやすいライブラリをご提供いただき、とても助かっています。

概要: Misskey サーバ側が原因で WebSocket 接続が切断された際に、`reconnect=True` の場合にも自動的に再接続されていないような挙動をする

サーバ側起因の問題で意図的に再現させることができないため、まだ十分に調査ができておりません。現在は `client.py` の `connect`, `_connect` 周りにブレークポイントを入れながら再現時の挙動を確認中です。

引き続き調査をしてみようと思いますが、もし既知の問題や良い調査方法などありましたらコメントいただけますと幸いです。

**Comment by yupix** [comment]
こんにちは、報告ありがとうございます。`reconnect=True` にしているとのことですが、 `on_reconnect` イベントは作成しているでしょうか? 私の記憶では、WebSocket自体は再作成するのですが、channelの再接続は自分で行う必要があったと思います。もし、使用されてない場合は以下のリンクのコードが参考になると思います。ご確認の程よろしくお願いします。

https://github.com/TeamBlackCrystal/akari/blob/main/main.py#L49

**Comment by yuma-m** [comment]
早速のコメント、どうもありがとうございます！

> `on_reconnect` イベントは作成しているでしょうか?

こちら見落としておりました。`on_reconnect` 内でチャンネルへの接続処理を追加して、再度挙動を見てみようと思います。問題ないようでしたら追って Close します。

**Comment by yuma-m** [comment]
上記修正したものを半日ほど動かした結果、`on_reconnect` でチャンネルへ再接続していなかったために、WebSocket 切断・再接続後に `on_note` が発火せず、WebSocket が切断されたままだと勘違いしていたようです。問題は解消しましたので、本件 Close します。どうもありがとうございました。
